### ISSUE TITLE
Implement cancellation mechanism in Reader

### ISSUE THREAD

**Issue by jsenn** [ifcquery/ifcplusplus#121]
It's currently not possible to cancel an Ifc import after it's been started. While it's possible for the user to implement this by subclassing AbstractReader, it'd be nice to have this functionality in the ReaderSTEP.

One way to do this would be to pass a `std::function<bool()>` object to the reader (or to its individual member functions) that returns `true` when cancellation is requested and `false` otherwise. This would be polled at appropriate times, and operations would be prematurely stopped when requested.

This may also apply to writers or geometry converters.

ETA: I'd be happy to implement this if there's interest.

**Comment by ifcquery** [comment]
For me it is not important at the moment, but if you implement it and submit a pull request, I can merge it.

**Comment by jsenn** [comment]
Closing; implemented in #133
