### ISSUE TITLE
build failed  and show “CARVE_EPSILON”: undeclared identifier

### ISSUE THREAD

**Issue by vfsd** [ifcquery/ifcplusplus#145]
include:
E:\OpenSourceGraph\OSG_install2\include
E:\Qt\Qt5.11.1\5.11.1\msvc2015_64\include
E:\IFC\Carve\include\2019
E:\IFC\IfcPlusPlusd\include\2019
E:\IFC\IfcPlusPlusGeometry\include
E:\IFC\boost_1_66_0\include

libs:
E:\OpenSourceGraph\OSG_install2\lib
E:\Qt\Qt5.11.1\5.11.1\msvc2015_64\lib
E:\IFC\Carve\lib
E:\IFC\IfcPlusPlusd\lib
E:\IFC\IfcPlusPlusGeometry\lib
E:\IFC\boost_1_66_0\lib

link input:
osgWidgetd.lib
osgVolumed.lib
osgUId.lib
osgTerraind.lib
osgSimd.lib
osgShadowd.lib
osgPresentationd.lib
osgParticled.lib
osgManipulatord.lib
osgFXd.lib
osgAnimationd.lib
OpenThreadsd.lib
osgd.lib
osgDBd.lib
osgUtild.lib
osgGAd.lib
osgViewerd.lib
osgTextd.lib
qtmaind.lib
osgQt5d.lib
Carved2019.lib
IfcPlusPlusd2019.lib
IfcPlusPlusGeometryd.lib
Qt53DAnimationd.lib
Qt53DCored.lib
Qt53DExtrasd.lib
Qt53DInputd.lib
Qt53DLogicd.lib
Qt53DQuickAnimationd.lib
Qt53DQuickd.lib
Qt53DQuickExtrasd.lib
Qt53DQuickInputd.lib
Qt53DQuickRenderd.lib
Qt53DQuickScene2Dd.lib
Qt53DRenderd.lib
Qt5AccessibilitySupportd.lib
Qt5AxBased.lib
Qt5AxContainerd.lib
Qt5AxServerd.lib
Qt5Bluetoothd.lib
Qt5Concurrentd.lib
Qt5Cored.lib
Qt5DBusd.lib
Qt5DesignerComponentsd.lib
Qt5Designerd.lib
Qt5DeviceDiscoverySupportd.lib
Qt5EdidSupportd.lib
Qt5EglSupportd.lib
Qt5EventDispatcherSupportd.lib
Qt5FbSupportd.lib
Qt5FontDatabaseSupportd.lib
Qt5Gamepad.lib
Qt5Gamepadd.lib
Qt5Guid.lib
Qt5Helpd.lib
Qt5Locationd.lib
Qt5Multimediad.lib
Qt5MultimediaQuickd.lib
Qt5MultimediaWidgetsd.lib
Qt5NetworkAuthd.lib
Qt5Networkd.lib
Qt5Nfcd.lib
Qt5OpenGLd.lib
Qt5OpenGLExtensionsd.lib
Qt5PacketProtocold.lib
Qt5PlatformCompositorSupportd.lib
Qt5Positioningd.lib
Qt5PositioningQuickd.lib
Qt5PrintSupportd.lib
Qt5Qmld.lib
Qt5QmlDebugd.lib
Qt5QuickControls2d.lib
Qt5Quickd.lib
Qt5QuickParticlesd.lib
Qt5QuickTemplates2d.lib
Qt5QuickTestd.lib
Qt5QuickWidgetsd.lib
Qt5RemoteObjectsd.lib
Qt5Scxmld.lib
Qt5Sensorsd.lib
Qt5SerialBusd.lib
Qt5SerialPortd.lib
Qt5Sqld.lib
Qt5Svgd.lib
Qt5Testd.lib
Qt5TextToSpeechd.lib
Qt5ThemeSupportd.lib
Qt5UiToolsd.lib
Qt5VulkanSupportd.lib
Qt5WebChanneld.lib
Qt5WebSocketsd.lib
Qt5WebViewd.lib
Qt5Widgetsd.lib
Qt5WindowsUIAutomationSupportd.lib
Qt5WinExtrasd.lib
Qt5Xmld.lib
Qt5XmlPatternsd.lib
qtfreetyped.lib
qtlibpngd.lib

C2065	“CARVE_EPSILON”: undeclared identifier  QtGuiApplication20190416	e:\ifc\ifcplus20190414\include\ifcpp\geometry\carve\geomutils.h	466

**Comment by ifcquery** [comment]
What are you trying to say here?
What is "OpenSourceGraph"? Do you mean OpenSceneGraph?
Please get your things in order before you post messages that no one can understand
