### ISSUE TITLE
IfcLineIndex: List of integers is being read as one single integer instead of a list of integers which causes errors (invalid stoi argument)

### ISSUE THREAD

**Issue by musonius** [ifcquery/ifcplusplus#147]
According to the specification of [IfcLineIndex](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/schema/ifcgeometryresource/lexical/ifclineindex.htm), it is a list of indices to define a line segment or a poly line. Unfortunately, the import of IFC++ treats it as a single integer.

Example lines of the attached IFC file I try to read with IFC++:

`#114= IFCCARTESIANPOINTLIST2D(((2073.375000,2497.404000),(2073.375000,0.),(0.,0.)));`
`#113= IFCINDEXEDPOLYCURVE(#114,(IFCLINEINDEX((1,2)),IFCLINEINDEX((2,3)),IFCLINEINDEX((3,1))),$);`

This is implemented in IfcPlusPlus/src/ifcpp/IFC4/include/IfcLineIndex.h as follows:

`// TYPE IfcLineIndex = LIST [2:?] OF IfcPositiveInteger;`
`class IFCQUERY_EXPORT IfcLineIndex : public IfcPositiveInteger, public IfcSegmentIndexSelect`

Deriving IfcLineIndex from IfcPositiveInteger and particularly the implementation of IfcLineIndex::createObjectFromSTEP in IfcPlusPlus/src/ifcpp/IFC4/lib/IfcLineIndex.cpp causes bad parsing errors:

`readInteger( arg, type_object->m_value );`

Reading the file in IfcQuery produces error messages like

`Error: ReaderSTEP::readEntityArguments, #113=IfcIndexedPolyCurve: invalid stoi argument`

The IFC file: 
[VW2019 Pset_Common_IsExternal IFC4.zip](https://github.com/ifcquery/ifcplusplus/files/3116794/VW2019.Pset_Common_IsExternal.IFC4.zip)

**Comment by musonius** [comment]
The same is true for IfcArcIndex as well.

The following diff file, which is based on IFC++ from Dezember 9, 2018, suggests a fix of the problem: 
[issue147.zip](https://github.com/ifcquery/ifcplusplus/files/3121165/issue147.zip)

**Comment by ifcquery** [comment]
I just committed a fix for this issue. The file should parse correctly now.
However, IfcLineIndex geometric representation is not implemented yet.
Contributions are welcome :)
If you are working on a commercial project and need the conversion of geometric items to Carve or OCC representation, I can schedule the task. Please contact me on ifcquery.com in that case.

**Comment by musonius** [comment]
Thank you! I'll test it as soon as I get back to work on Monday.
