### ISSUE TITLE
IfcCartesianPointList3D

### ISSUE THREAD

**Issue by Cafougnette** [ifcquery/ifcplusplus#150]
Hello,
this [class](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/link/ifccartesianpointlist3d.htm) has changed in IFC 4x1 and has a new optional member : TagList.
But IfcCartesianPointList3D.h files does not have this member and expect only one parameter 
virtual size_t getNumAttributes() { return 1; }
Thank you.

**Comment by ifcquery** [comment]
Meanwhile, the IFC version has changed to 4x1, so the attribute TagList is now there.
