### ISSUE TITLE
Error exporting IFCSIUNIT

### ISSUE THREAD

**Issue by JPTron** [ifcquery/ifcplusplus#157]
With the following code:

> shared_ptr<IfcSIUnit\> si_unit = std::make_shared<IfcSIUnit\>();
> si_unit->m_UnitType = std::make_shared<IfcUnitEnum\>(IfcUnitEnum::ENUM_LENGTHUNIT);
> si_unit->m_Name = std::make_shared<IfcSIUnitName\>(IfcSIUnitName::ENUM_METRE);
> ifc_model->insertEntity(si_unit);

IFCSIUNIT is exported as:

> #6= IFCSIUNIT($,.LENGTHUNIT.,$,.METRE.);

most probably because of:

> if( m_Dimensions ) { stream << "#" << m_Dimensions->m_entity_id; } else { stream << "$"; }

in:

> IfcSIUnit::getStepLine

Apparently, it should instead be exported as:

> #6= IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);

or at least, it's what Revit seems to expect:

> /*     13 */ #6= IFCSIUNIT($
> ---------------------------^
> *** Recoverable Error: Redefined Attribute should be a '*' *** on line 13.

**Comment by ifcquery** [comment]
fixed with latest commit
