### ISSUE TITLE
Build fails on Ubuntu 18

### ISSUE THREAD

**Issue by Baehn** [ifcquery/ifcplusplus#158]
Hello,

I installed all dependencies and "cmake" runs without error. However "make" fails with the following error:

```
/ifcplusplus/IfcPlusPlus/src/external/XUnzip.h:372:19: error: ‘HZIP’ was not declared in this scope
 bool IsZipHandleU(HZIP hz);
```

I was not able to figure out where hzip comes from. Any help much appreciated!

**Comment by ifcquery** [comment]
should be fixed with the latest commit

**Comment by berndhahnebach** [comment]
If you still have problems you may give this a try: https://github.com/berndhahnebach/ifcplusplus

It compiles and runs on Debian Buster

**Comment by Baehn** [comment]
now it is working, thank you very much!
