### ISSUE TITLE
GeometrySettings.h Error C2942

### ISSUE THREAD

**Issue by Anzai1028** [ifcquery/ifcplusplus#165]
When I build SimpleViewerExampleMFC with VS2013, error occurs;
**GeometrySettings.h(158): error C2942: “std::shared_ptr<IfcObjectDefinition>”: The template class id is redefined as the formal parameter of the function.**

_Does anyone know how to solve this problem?_

**Comment by ifcquery** [comment]
Sorry, VS2013 is 7 years old. I recommend to always use up to date compilers.
