### ISSUE TITLE
SimpleViewerExampleQt fails to compile

### ISSUE THREAD

**Issue by fpuech** [ifcquery/ifcplusplus#166]
Before going into the details I want to say that this is a great project. I just got the latest changes and the SimpleViewerExampleQt fails to compile with the following error:

`carve\representationconverter.h(1076): note: Reason: cannot convert from 'IfcElement *' to 'const std::shared_ptr<BuildingEntity>' (compiling source file src\gui\TabView.cpp)`

**Comment by ifcquery** [comment]
ok, should work now
