### ISSUE TITLE
Please tag the repo for package versions.

### ISSUE THREAD

**Issue by sanderboer** [ifcquery/ifcplusplus#172]
Hi,

like the title says, I am creating a package template for void linux and the community prefers to follow the upstream release version scheme.

Is the absence of releases an established protocol in the organization ? If so, we can follow the scheme of another major distro, but we prefer not to.

gr.
Sander

**Comment by ifcquery** [comment]
Hi,
I just created a release, kinda makes sense :)

**Comment by berndhahnebach** [comment]
you could name it 1.0.0

**Comment by berndhahnebach** [comment]
BTW: if you start with 0.x somewhat you may never reach 1.x. FreeCAD is 18 years old project has thousands of commits but is at 0.19 :-(
