### ISSUE TITLE
IfcPlusPlus doesn't properly handle file name encodings

### ISSUE THREAD

**Issue by jsenn** [ifcquery/ifcplusplus#173]
On my machine I have a file called "汉.ifc". Attempting to open this file in the Qt viewer (as well as in my Qt-based application) fails. I think this is due to improper handling of locales in ReaderSTEP.cpp. There we find the following code:
```c++
	// open file
	std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> StringConverter;
	std::string filePathStr = StringConverter.to_bytes(filePath);

	if( !(setlocale(LC_ALL, "en-US") || setlocale(LC_ALL, "en_us.UTF-8") ||  setlocale(LC_ALL, "en_US.utf8")))
	{
		std::wstringstream strs;
		strs << L"setlocale failed" << std::endl;
		messageCallback(strs.str().c_str(), StatusCallback::MESSAGE_TYPE_WARNING, __FUNC__);
	}
	else
	{
		char* buf = nullptr;
		size_t len = std::wcstombs(buf, filePath.c_str(), 0);
		buf = new char[len + 1];
		std::wcstombs(buf, filePath.c_str(), (len + 1) * 6);
		filePathStr = buf;
		delete[] buf;
	}
	std::ifstream infile(filePathStr.c_str(), std::ifstream::in);
```
This code takes the user's given file path as a wide string (assumed to be encoded in UCS2), and converts it using `std::wstring_convert` into a UTF-8 string. Then, a series of `setlocale` calls are tried, one after the other, stopping after the first one succeeds. If none of them succeed, it throws a warning and uses the previously converted UTF-8 string. But if any succeed, the conversion to UTF-8 is done again, this time using `std::wcstombs`.

What happens on my machine is that the first `setlocale` call succeeds, so now the locale is `en-US`. But that means that the `std::wcstombs` call fails, because the 汉 character doesn't exist in that locale. Thus, `len` [is set to](https://en.cppreference.com/w/cpp/string/multibyte/wcstombs) `size_t(-1)`, so `buf` has a size of 0, and the file isn't opened.

Now, if you reorder the `setlocale` calls such that either the "en_us.UTF-8" or "en_US.utf8" variant comes first, the code successfully opens the file. But neither of those strings is an actual locale, at least on my reading of [the documentation](https://docs.microsoft.com/en-us/cpp/c-runtime-library/locale-names-languages-and-country-region-strings). I think they work simply because the fallback locale is used, since the code works equally well if I replace the `setlocale` calls by `setlocale( LC_ALL, "qx_QX" )`, which is obviously not a real locale name...

One possible solution here is to change the `if` condition to read `!( setlocale( LC_ALL, "English_United States.65001" ) || setlocale( LC_ALL, "en-US" ) )`. But a larger question is **why do this `setlocale` stuff at all**? Presumably this is important to get commas and decimals straight, but that is already done in `readData`, which properly scopes the locale change to `LC_NUMERIC`, and cleans up after itself when it's done. From what I can see, it'd be more robust and clear to just use the string returned by the `wstring_convert`er.

**Comment by jsenn** [comment]
After some more testing, the only solutions that work for me are:
1. Use `std::wcstombs` after a `setlocale(LC_ALL, "English_United States.65001")` call (in fact, the locale string ".utf8" works just as well, and on my machine is equivalent to the "English_United States.65001" string).
2. Pass the `wstring` directly to `std::ifstream`. The `wstring` overload only exists on Windows though, so this might have to be hidden behind some kind of wrapper.

**Comment by SHIHUAMarryMe** [comment]
you can do this, make ifc lib support chinese.
`	// open file
	std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> StringConverter;
	std::string filePathStr = StringConverter.to_bytes(filePath);

	if( !(setlocale(LC_ALL, "en-US") || setlocale(LC_ALL, "en_us.UTF-8") ||  setlocale(LC_ALL, "en_US.utf8")))
	{
		std::wstringstream strs;
		strs << L"setlocale failed" << std::endl;
		messageCallback(strs.str().c_str(), StatusCallback::MESSAGE_TYPE_WARNING, __FUNC__);
	}
	else
	{

               **setlocale(LC_ALL, ".936");**

		char* buf = nullptr;
		size_t len = std::wcstombs(buf, filePath.c_str(), 0);
		buf = new char[len + 1];
		std::wcstombs(buf, filePath.c_str(), (len + 1) * 6);
		filePathStr = buf;
		delete[] buf;
	}
	std::ifstream infile(filePathStr.c_str(), std::ifstream::in);`
