### ISSUE TITLE
RelatingPriorities cardinality

### ISSUE THREAD

**Issue by claimred** [ifcquery/ifcplusplus#174]
- According to IFC documentation IfcRelConnectsPathElements.RelatingPriorities has a L[0:?] cardinality i.e. it's a mandatory attribute that should be provided yet it's ok for it to be empty.

- According to https://github.com/ifcquery/ifcplusplus/blob/master/IfcPlusPlus/src/ifcpp/writer/WriterUtil.h#L39 IFC++ writes empty RelatingPriorities vector as $ in the file hence it violates L[0:?] requirment, it should be () instead. ifccheckingtool-lite reports it as 

![image](https://user-images.githubusercontent.com/7941502/78159925-eadde000-744b-11ea-8e92-ea554b7ab00b.png)
 

What am I missing here? Thanks!

**Comment by ifcquery** [comment]
Thanks for the report!
Should be fixed by latest commit. Please report if it persists.

**Comment by claimred** [comment]
@ifcquery Thanks! I'll take a look asap. 

I was wondering what's ifc++ release policy? Is it ok for library clients to use master HEAD right now or should one wait for release?

**Comment by ifcquery** [comment]
master HEAD is ok to use. I don't create a release after each fix like this or small improvement.

**Comment by claimred** [comment]
@ifcquery Hello. It looks like there is another case with optional containers, Like TagList in `IFCCARTESIANPOINTLIST3D`. It's serialized as `()` when it should be `$`.

https://github.com/ifcquery/ifcplusplus/blob/master/IfcPlusPlus/src/ifcpp/IFC4/lib/IfcCartesianPointList3D.cpp#L50

**Comment by ifcquery** [comment]
I just fixed those $ exports for optional list attributes when empty. Please let me know if it does not work
