### ISSUE TITLE
SimpleViewerExampleMFC cannot Compile 

### ISSUE THREAD

**Issue by jason-VV** [ifcquery/ifcplusplus#177]
ifcQueryDoc.cpp 
line 191:"m_converter_coin->convertToCoin3D( m_geometry_converter->getShapeInputData(), m_model_node.get() );"

line 200:"m_converter_coin->addNodes( objects_outside_spatial_structure, sw_objects_outside_spatial_structure );"

src \ IfcQueryDoc.cpp (191): error C2664: "void ConverterCarve2Coin3D :: convertToCoin3D (const std :: map <int, std :: shared_ptr <ProductShapeData>, std :: less <int>, std :: allocator <std: : pair <const _Kty, _Ty >>> &, SoSeparator *) ”: Unable to change parameter 1 from“ std :: map <std :: string, std :: shared_ptr <ProductShapeData>, std :: less <_Kty>, std :: allocator <std :: pair <const _Kty, _Ty >>> "is converted to" const std :: map <int, std :: shared_ptr <ProductShapeData>, std :: less <int>, std :: allocator <std :: pair <const _Kty, _Ty >>> & ”
1> with
1> [
1> _Kty = int,
1> _Ty = std :: shared_ptr <ProductShapeData>
1>]
1> and
1> [
1> _Kty = std :: string,
1> _Ty = std :: shared_ptr <ProductShapeData>
1>]
1> and
1> [
1> _Kty = int,
1> _Ty = std :: shared_ptr <ProductShapeData>
1>]

Does anyone know the reason? thank you ~

**Comment by ifcquery** [comment]
fixed with latest commit

**Comment by jason-VV** [comment]
thank you very much!

**Comment by jason-VV** [comment]
> fixed with latest commit

thank you very much!
