### ISSUE TITLE
If open more than 3 files, will throw carve::exception.

### ISSUE THREAD

**Issue by SHIHUAMarryMe** [ifcquery/ifcplusplus#178]
I invoke ifcplusplus in my project. I want to translate my ifc files to gltf file.
So I invoke ifcplusplus' API to parse ifc file, when it start parsing third file will throw carve::exception.
If I just parse the file just once, it's ok.
And I also try to use SimpleViewerExampleQt to load file, if load one file 3 times, the app also will broken down.
I trace the code, suspect when model is not closure, carve lib can not triangulate the model.
but I do not how to resolve this problem.
do you have some ideas?

**Comment by ifcquery** [comment]
Fixed with latest update. Thanks for the hint!
