### ISSUE TITLE
IfcTriangulatedFaceSet.PnIndex cardinality

### ISSUE THREAD

**Issue by UsoltsevaM** [ifcquery/ifcplusplus#180]
Hello,

According to IFC documentation IfcTriangulatedFaceSet.PnIndex attribute is optional. It has cardinality - ? L[1:?]. IfcPlusPlus serializes this attribute as empty container '()', while it should be '$' if PnIndex value is not provided. 
Related reference to IfcPlusPlus source - https://github.com/ifcquery/ifcplusplus/blob/master/IfcPlusPlus/src/ifcpp/IFC4/lib/IfcTriangulatedFaceSet.cpp#L77

Similar problem with IfcCartesianPointList3D.TagList was mentioned in issue https://github.com/ifcquery/ifcplusplus/issues/174#issuecomment-628836936.

Could you please have a look at these issues?
Thank you in advance.

**Comment by ifcquery** [comment]
Hi, this is fixed with the last update.
