### ISSUE TITLE
Memory Allocation

### ISSUE THREAD

**Issue by renvenuti** [ifcquery/ifcplusplus#182]
I've seen that for the creation of the Entities when parsing the ifc file you use a function EntityFactory:createEntityObject that return a lambda with a new call. After, you assign a returned pointer to a std::shared_ptr.
When tou do so, a double allocation is made, one for the entity by the new call, and one for a control block.
Reading large ifc files this is time consuming.
If you use std::make_shared, only one allocation is made.

Thanks

**Comment by ifcquery** [comment]
You mean line 698 in ReaderSTEP I guess. 
It is a direct assignment to shared_ptr<BuildingEntity>, which is the same thing as using std::make_shared. 
Where do you see a double allocation?

**Comment by renvenuti** [comment]
Hi

https://stackoverflow.com/questions/20895648/difference-in-make-shared-and-normal-shared-ptr-in-c
Bye

Inviato da iPhone

Il giorno 2 giu 2020, alle ore 14:47, ifcquery <notifications@github.com> ha scritto:

﻿

You mean line 698 in ReaderSTEP I guess.
It is a direct assignment to shared_ptr, which is the same thing as using std::make_shared.
Where do you see a double allocation?

**Comment by ifcquery** [comment]
did you try the changes that you suggest? Does it compile, is there a measurable performance improvement?

**Comment by renvenuti** [comment]
https://m.youtube.com/watch?v=Ywehms9PtVY

Inviato da iPhone

Il giorno 2 giu 2020, alle ore 16:01, ifcquery <notifications@github.com> ha scritto:

﻿

did you try the changes that you suggest? Does it compile, is there a measurable performance improvement?

**Comment by ifcquery** [comment]
I just tried make_shared:
shared_ptr<BuildingEntity> obj = std::make_shared<BuildingEntity>( EntityFactory::createEntityObject( entity_name_upper ) );

But the compiler complaints: 
error C2259: 'BuildingEntity': cannot instantiate abstract class

So it is not possible in this case, to use make_shared.
Also I did a performance test by introducing a second shared_ptr variable and assigning the same object. There was no measurable difference when loading 300k objects.

Please test and verify before you suggest changes!

**Comment by renvenuti** [comment]
﻿You need to replace the new inside the map for all ifc types with make_shared<ifcType>(). createEntityObject returns shared_ptr<BuildingEntity>.
Bye

Inviato da iPhone

Il giorno 2 giu 2020, alle ore 17:38, ifcquery <notifications@github.com> ha scritto:

﻿

I just tried make_shared:
shared_ptr obj = std::make_shared( EntityFactory::createEntityObject( entity_name_upper ) );

But the compiler complaints:
error C2259: 'BuildingEntity': cannot instantiate abstract class

So it is not possible in this case, to use make_shared.
Also I did a performance test by introducing a second shared_ptr variable and assigning the same object. There was no measurable difference when loading 300k objects.

Please test and verify before you suggest changes!

**Comment by ifcquery** [comment]
As I said, the performance difference is not measurable. I tested it.

I can assure you, that one assignment to a variable is a millionth of the computational cost of processing one entity. The geometry is a million times more expensive.

If you want to contribute, you are welcome to improve internal structures in the CSG library Carve!

**Comment by renvenuti** [comment]
Ok, thanks for your attention

Bye

Inviato da iPhone

Il giorno 2 giu 2020, alle ore 18:25, ifcquery <notifications@github.com> ha scritto:

﻿

As I said, the performance difference is not measurable. I tested it.

I can assure you, that one assignment to a variable is a millionth of the computational cost of processing one entity. The geometry is a million times more expensive.

If you want to contribute, you are welcome to improve internal structures in the CSG library Carve!
