### ISSUE TITLE
MVD support

### ISSUE THREAD

**Issue by claimred** [ifcquery/ifcplusplus#184]
Hi!

I was wondering if ifcpp had any plans to support standard Model View Definitions in some way. If I understand correctly Reference View has a severely different EXPRESS schema, so using code c++ code generation will result in a completely different class hierarchy 🤔 

There is mvdxml being developed by bSI but it is used for checking purposes if I get this right. 

https://forums.buildingsmart.org/t/ifc4-rv-1-2-shcema-issue/2049/4

**Comment by ifcquery** [comment]
https://technical.buildingsmart.org/standards/ifc/mvd/

**Comment by claimred** [comment]
>https://technical.buildingsmart.org/standards/ifc/mvd/

Thanks, I am aware of MVD documentation website. My question was about IfcPlusPlus's plans to support MVD from the technical point of view, like making mvd a part of the library.

**Comment by ifcquery** [comment]
IFC++ supports the complete set of entities. You can select any subset, electrical, mechanical etc.
