### ISSUE TITLE
Express Functions and Conditions

### ISSUE THREAD

**Issue by gianks** [ifcquery/ifcplusplus#186]
Hi,
Express allows to declare constraints (as where conditions, optionality and cardinality of parameters for example) and functions.
These could be parsed and translated in C++ code which would help way more than a flat set of classes!

Can you please evaluate to add such functionality to your parser?
Thanks!

**Comment by ifcquery** [comment]
Hi,
at the moment, optionality and cardinality is not handled strictly during import. If you need this feature, I can implement it for you with a freelance contract.
