### ISSUE TITLE
Reading geometry

### ISSUE THREAD

**Issue by SanctumDesert** [ifcquery/ifcplusplus#188]
Hello,

currently I am using IfcPlusPlus without the GUI to read in IFC files.
I'm trying to figure out, how i can get informations about an IfcWall, for example the coordinates of this wall.
If this question is wrong here, please inform me and delete it. :)

Best regards,
Lukas

**Comment by shaheer34mts** [comment]
Hey, did you find any solution to this ?

**Comment by ifcquery** [comment]
See examples/LoadFileExample
