### ISSUE TITLE
A problem in GeometryConverter.h

### ISSUE THREAD

**Issue by dbshch** [ifcquery/ifcplusplus#196]
I'm updating the ifcplusplus for my project from a very old version. But when using the function convertGeometry() (line 294, IfcPlusPlus/src/ifcpp/geometry/Carve/GeometryConverter.h), I find that all the objects are in the m_map_outside_spatial_structure.
To be added to the spatial structure, the ifc_product in line 136 should be a "IfcProduct". However, this value is assigned in line 352 and 365, which means ifc_product must be a "IfcProject". A "IfcProject" class can't be casted to "IfcProduct" (or did I miss something?), therefore the function "resolveProjectStructure" actually never really executed and all objects are outside spatial structure.

In the old (several years ago) version it also handles the ifc_product when the object isn't a "IfcProduct" so everything works fine. Is this a bug or I am using a outdated method to convert products?

**Comment by ifcquery** [comment]
Should be solved now

**Comment by dbshch** [comment]
Thanks a lot.
