### ISSUE TITLE
Whitespace symbols in STEP lines

### ISSUE THREAD

**Issue by claimred** [ifcquery/ifcplusplus#198]
Is there a specific reason to put whitespace after the equals sign (#23=_IFCOLUMN)? For example https://github.com/ifcquery/ifcplusplus/blob/master/IfcPlusPlus/src/ifcpp/IFC4/lib/IfcColumn.cpp#L65 (every `::getStepLine` function works like that)

Not writing spaces could easily save a hundred kilobytes on large ifc projects. Not that much one could argue, but everything matters in large projects.

**Comment by ifcquery** [comment]
Solved with latest update
