### ISSUE TITLE
Invalid comparator: FaceStitcher::EdgeOrderData::Cmp

### ISSUE THREAD

**Issue by Sydra7** [ifcquery/ifcplusplus#204]
It creates undefined behavior in std::sort.

![regregearg](https://user-images.githubusercontent.com/64328252/101494650-e6b57b00-3967-11eb-94c8-b424a112c6c7.png)

**Comment by ifcquery** [comment]
FaceStitcher::EdgeOrderData is a part of carve, which is a third party library. 
If you find a solution, you are welcome to share ;)
