### ISSUE TITLE
C API or .NET wrapper

### ISSUE THREAD

**Issue by arturred** [ifcquery/ifcplusplus#222]
Hi
I would like to use this library in other languages but cannot use C++ directly (Delphi, .NET). Is there a wrapper or C API header that exposes the minimum functionality to open IFC files and view them in 3D?

**Comment by ifcquery** [comment]
Hi, 
a .NET API is not implemented yet, and not a priority right now.
There are some open source C# implmentations to read IFC files, for example https://github.com/GeometryGym/GeometryGymIFC
