### ISSUE TITLE
IFCREINFORCINGBAR not showing

### ISSUE THREAD

**Issue by dbshch** [ifcquery/ifcplusplus#228]
I met a issue that some IFCREINFORCINGBAR elements are not showing. Some works, but some are missing. I tested the sample file below with the newest example program, nothing showed.

It seems that the vertices in the resolved mesh set are all zero points.

It would be great if you can take a look at it. Thanks.

[bartest.txt](https://github.com/ifcquery/ifcplusplus/files/8711270/bartest.txt)

**Comment by dbshch** [comment]
sweep.h line 321:

The rotation of 0 and 180 should be taken care of.

**Comment by ifcquery** [comment]
this is fixed meanwhile
