### ISSUE TITLE
Missing openings

### ISSUE THREAD

**Issue by carmenfan** [ifcquery/ifcplusplus#230]
Hi,

I'm trying to evaluate the library to replace IFCOpenShell and have come into a model where the wall isn't extruded for the windows:

![image](https://user-images.githubusercontent.com/11945337/173799818-4ed8d8ed-ec4b-4224-a4e6-184534a8ab5d.png)

what it looks like on BIM vision: 
![image](https://user-images.githubusercontent.com/11945337/173799975-602a8979-be99-478c-8de0-50cab25f7d7d.png)

Model used: [duplex.zip](https://github.com/ifcquery/ifcplusplus/files/8908106/duplex.zip)

I saw https://github.com/ifcquery/ifcplusplus/issues/210 and thought it might be related so I tried a range of epsilon values (1e-1 to 1e-15), and also retriangulating the mesh set as suggested [here ](https://github.com/ifcquery/ifcplusplus/issues/210#issuecomment-842302645), but none of which has got me closer to what I want to see. So I started to wonder if it is not the same issue.

Any help/pointers would be much appreciated!

**Comment by ifcquery** [comment]
Hi,
I'm aware that the boolean operations with Carve have some issues.
I tried different epsilons, also normalizing the meshes before bool ops.
Doesn't work perfectly yet...
With some funding I could spend some time on improving the mesh quality by merging coplanar faces etc.

**Comment by carmenfan** [comment]
@ifcquery  thanks for your quick reply!

If the problem is on Carve, does that mean that I might be able to make it work if I recompile it with OpenCascade?

**Comment by ifcquery** [comment]
OpenCascade is not fully implemented in IFC++.
Meshes need to be converted to OCC in CSG_Adapter::computeCSG in case Carve fails. 
Sometimes it is not possible to detect a failure in a CSG operation, the mesh is just not correct.

**Comment by ifcquery** [comment]
If you want, you cant contribute some implementations, but simply recompile with OCC won't do it
