### ISSUE TITLE
IFC4X3RC1 branch does not support reading "IFCBuildingElement" even with IFC files before version IFC4X3RC1

### ISSUE THREAD

**Issue by alas2** [ifcquery/ifcplusplus#233]
In IFC4X3RC1, "IFCBuildingElement" renamed to "IfcBuiltElement", IFC4X3RC1 branch does not support 'IFCBuildingElement' but for backward compatibility, I think it needs to be supported.

Probably, in IfcPlusPlus/src/ifcpp/IFC4/EntityFactory.cpp file line ~ 887 need to add this

{ "IFCBUILDINGELEMENT", []()->BuildingEntity* { return new IfcBuiltElement(); } },

**Comment by ifcquery** [comment]
IFC4X3 is now in the master branch, this issue should be resolved
