### ISSUE TITLE
Earcut vs Carve vertices order issue?

### ISSUE THREAD

**Issue by ptlprg** [ifcquery/ifcplusplus#237]
Hi,

Since the commit https://github.com/ifcquery/ifcplusplus/commit/989c262fa91f3d98e0f1a5b65a8ad583ad0fcd71, my app using IfcPlusPlus runs into the following issue.

I'm relying on vertices order to identify "upper" and "lower" faces (I'm only interested in these) of building elements. This used to be reliable (anticlockwise vertices = upper face, clockwise = lower).

Unfortunately, starting from the mentioned commit, it's not anymore. For some objects, lower faces' vertices are now in anticlockwise order (with normals [0,0,1]), whereas they used to be in clockwise order (with normals [0,0,-1]), effectively breaking my app.

Is there a setting I need to play with to fix this?

If not, is there a smarter way to identify "upper" and "lower" building element faces?

Thanks

**Comment by ifcapps** [comment]
Hi,
the only reliable way is to compute the normal vectors, which is easy 10 lines of code.

**Comment by ptlprg** [comment]
I'm talking about shapes converted by OSG with :
`converter_osg->convertToOSG(geometry_converter->getShapeInputData(), model_switch);`
Shouldn't the normal vectors already be computed?

I'm having this new issue on "some" shapes, but most of them are still fine by the way. Although it seems all my test IFC files are impacted.

For instance, if you look at the beam "05UlD$Pjn5AAF$ede_n7Jx" from this file : 
[Architecture_anon.zip](https://github.com/ifcquery/ifcplusplus/files/9838328/Architecture_anon.zip)
After the conversion to OSG, all "horizontal" faces (2 upper and 1 lower) have their vertices in anticlockwise order, with same normal vectors (0,0,1). Since they are sharing the same normal vector, I don't see how to use it to identify upper from lower faces. Before the mentioned commit, the lower face vertices were in clockwise order, with normal vector (0,0,-1), which was fine.

**Comment by ifcquery** [comment]
Yes, the normals are computed automatically.
If you find a bug in the code, let me know!

**Comment by ptlprg** [comment]
All I'm saying is, for the specific beam mentioned in my previous comment, the lower face vertices used to be in clockwise order with normals (0,0,-1), and since the commit mentioned in my initial comment they are in anticlockwise order with normals (0,0,1).

The last SimpleViewerExample displays that beam properly, so I guess it's technically not a bug.

But one can't rely anymore on normal vectors and/or vertices order to identify opposite faces, which is a major problem for my app as it needs to identify load bearing faces and their opposite faces.

How can one identify opposite faces now?
