### ISSUE TITLE
error compiling IfcPlusPlus1.2 in c++17

### ISSUE THREAD

**Issue by yacsha** [ifcquery/ifcplusplus#239]
Hello
I use Visual C++ 2017 compiler, set to c++17 language

When compiling IfcPlusPlus1.2 I get the following errors:

- error C2672: 'std::toupper': no matching overloaded function found (compiling source file src\ifcpp\IFC4X3\TypeFactory.cpp)
- error C2780: '_Elem std::toupper(_Elem,const std::locale &)': 2 arguments expected; 1 provided (by compiling source file src\ifcpp\IFC4X3\TypeFactory.cpp)

Apparently it was a problem with the [toupper overload](https://stackoverflow.com/questions/7131858/stdtransform-and-toupper-no-matching-function). Following that recommendation, it was solved by changing line 602:
`std::toupper(c) to ::toupper(c)`

It would be good to analyze this case and be corrected in the next version. 

Regards.

**Comment by ifcquery** [comment]
Hi, 
I can't confirm the issue. Current version compiles fine with VS 2022, and also with gcc on Ubuntu.

**Comment by yacsha** [comment]
In visual c++, did you test it with this language setting for C++17?
![image](https://user-images.githubusercontent.com/2723954/207725492-48c28adb-0665-4a63-b1a1-3d79a999483b.png)

**Comment by ifcquery** [comment]
Current version 1.3 should compile with C++ 17
