### ISSUE TITLE
IfcMapConversion is printed with 10 parameters instead of the 8 indicated in IFC4x3

### ISSUE THREAD

**Issue by yacsha** [ifcquery/ifcplusplus#240]
Hello
IfcMapConversion is printed with 10 parameters [instead of the 8 indicated in IFC4x3](http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcMapConversion.htm):
Currently it prints like this:
`#19= IFCMAPCONVERSION(#17,#18,126570.,1286965.,$,$,$,$,$,$);`
Apparently it is due to the m_ScaleX and m_ScaleY variables that do not exist in the current ifc4x3 standard

Apparently these variables have been passed to IfcMapConversionScaled, which does not currently exist in ifcplusplus 1.2
https://github.com/buildingSMART/IFC4.3.x-development/issues/533
http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcMapConversionScaled.htm

Regards

**Comment by ifcquery** [comment]
Hi,

I used  IFC4.3 TC1, you are referencing IFC4.3.1.x dev
https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/

I don't want to use intermediate development schemas, because they change very often.

**Comment by yacsha** [comment]
I confirm that this issue has been fixed using the `IFC4 schema`. Tested with ifcplusplus version 2.5, and it appears to have been fixed since version 1.9. Thank you.
