### ISSUE TITLE
Bug in readEntityArguments when ENABLE_OPENMP

### ISSUE THREAD

**Issue by ExternPointer** [ifcquery/ifcplusplus#244]
There is some code in the method for compatibility with old IFC formats.
File: ReaderSTEP.cpp, line 649
<img width="1263" alt="image" src="https://github.com/ifcquery/ifcplusplus/assets/30197413/05fa2844-76cd-4f70-a1fa-26033cc4318b">

This code can not works in parallel, because one style can be related to several entities. As a result we have broken styles:
![image](https://github.com/ifcquery/ifcplusplus/assets/30197413/762486da-df71-42bf-ba98-d5ec5b9bb6c4)

PROPOSITION: Parse file as usual and then "tweak" styles (just move this code to new loop after OMP section). Result:
<img width="799" alt="image" src="https://github.com/ifcquery/ifcplusplus/assets/30197413/4c05925e-b185-4b21-a890-a8adac8d9180">

Fixed method:
https://gist.github.com/ExternPointer/1ccd55f3e9fec1eb37236a06dbe5d68e

**Comment by ifcquery** [comment]
Thanks for the hint!
I will include the fix in the next release.
