### ISSUE TITLE
Missing geometry data when loading a ifc file in IFC++Viewer 1.7, but works correctly in IFC++Viewer 1.1

### ISSUE THREAD

**Issue by thuytran1676** [ifcquery/ifcplusplus#246]
Steps to reproduce: 
1. Launch solution SimpleViewerExampleQt
2. Load file Heidelberg_Mustang_IFC_Rev2.ifc
Actual Result: Missing a lot of geometry in IFC++Viewer 1.7 (see attached file IFC++VIewer_1.7.png)
Expected Result: should be the same as what showed up in IFC++VIewer1.1 (see attached file IFC++Viewer_1.1.png)

![IFC++VIewer_1 7](https://github.com/ifcquery/ifcplusplus/assets/139486000/5ef2ca7a-e9c7-4118-bb48-835aeb49cddb)
![ICF++Viewer_1 1](https://github.com/ifcquery/ifcplusplus/assets/139486000/88d0600d-10b2-428d-a28c-2913cfb08776)
[Heidelberg_Mustang_IFC_Rev2.zip](https://github.com/ifcquery/ifcplusplus/files/12052099/Heidelberg_Mustang_IFC_Rev2.zip)

**Comment by ifcquery** [comment]
There was a bug. Fixed with latest release 1.8
