### ISSUE TITLE
import ifc  FaceConverter::createTriangulated3DFace failed

### ISSUE THREAD

**Issue by lauming** [ifcquery/ifcplusplus#249]
The cylindrical surface is described using the IFCCYLINDRICALSURFACE node. However, the triangulation process after projecting the cylindrical surface is incorrect.
the version: 1.6

![Snipaste_2023-08-01_14-44-08](https://github.com/ifcquery/ifcplusplus/assets/17967280/444c33ef-bc7e-4e93-95c4-5693f6f5b207)
![Snipaste_2023-08-01_15-00-17](https://github.com/ifcquery/ifcplusplus/assets/17967280/d299f49a-8d72-4597-81ea-944c42fc9cdb)
[rst_basic_sample_project2-AdvancedBrep.zip](https://github.com/ifcquery/ifcplusplus/files/12225543/rst_basic_sample_project2-AdvancedBrep.zip)

**Comment by ExternPointer** [comment]
I found a partial solution that works well for this example and is possible for many others as well. The idea is to take all the surfaces and calculate the intersection using CSG

![image](https://github.com/ifcquery/ifcplusplus/assets/30197413/484ca615-ad53-4fd8-94fd-7fd05ed38929)

**Comment by ExternPointer** [comment]
After some experiments I can say that my idea is very bad

**Comment by ifcquery** [comment]
With the latest release, this issue is solved
