### ISSUE TITLE
Missing corner pipes.

### ISSUE THREAD

**Issue by thuytran1676** [ifcquery/ifcplusplus#251]
Load file "Mec AG Yard Piping.ifc" in IFC++Viewer 1.8. This ifc file had been exported from a Revit SelectionSet collection, hence all geometry data is outside spatial structure and max model bounding box is super tiny (0.157, -0.997, 0.025).

Actual result: almost corner pipes are lost. 
![image](https://github.com/ifcquery/ifcplusplus/assets/139486000/2e01bd26-185d-4936-8711-865ede4a427b)

Expected result: 
![image](https://github.com/ifcquery/ifcplusplus/assets/139486000/7a08399b-581e-4fba-bdef-526e87004d12)

Because compress model file to be a .zip file is greater than 25 MB, hence have to compress it to be a .7z, then added .zip extension file so that can drop it in to the ticket. To revert the process, pls remove the .zip extension file to be just a .7z, then use 7-zip to extract it to be a .ifc file.
[Mec AG Yard Piping.7z.zip](https://github.com/ifcquery/ifcplusplus/files/12441509/Mec.AG.Yard.Piping.7z.zip)

**Comment by ifcquery** [comment]
There is still room for improvement for some geometry implementations.
In case it is a commercial project, I can fix and complement any geometry type.
So far, all geometry issues with customers that use the library, have been solved.
You can contact me for an offer for specific models/geomety types. Contact details are here: https://ifcquery.com/
