### ISSUE TITLE
Insert IFC at specific coordinates into another IFC

### ISSUE THREAD

**Issue by yacsha** [ifcquery/ifcplusplus#252]
It is possible to Insert an IFC inside another IFC, specifying the insertion coordinates x, y, z with respect to the destination IFC? 

If possible, will there be some example code to do it?

Best regards

**Comment by ifcquery** [comment]
Yes of course it is possible. There are no such examples that I am aware of.
If you need help with implementations, I can make an offer. Feel free to use the contact information: https://ifcquery.com/
