### ISSUE TITLE
ifc4 mesh error 

### ISSUE THREAD

**Issue by ratel12104** [ifcquery/ifcplusplus#254]
![image](https://github.com/ifcquery/ifcplusplus/assets/148205184/829dc003-695c-4621-9839-ed0d35a0a81b)
when open ifc4 in viewer mesh error
but ifc2X3 no errors

**Comment by ratel12104** [comment]
> Hi. Can you attach IFC file?

[pipe.zip](https://github.com/ifcquery/ifcplusplus/files/13004534/pipe.zip)

**Comment by ifcquery** [comment]
I can confirm that there are still problems with some geometric items.
Espescially with triangulation of curved surfaces like NURBS surfaces.
Contributions are welcome :)

**Comment by ratel12104** [comment]
How to solve it？

**Comment by ifcquery** [comment]
With the latest release, this type of geometry is improved, but still not perfect.
If it is important, I can make an offer to fully implement the remaining issues.
In case you are interested, please contact me at www.ifcquery.com
