### ISSUE TITLE
Request for original source code

### ISSUE THREAD

**Issue by emvivre** [ifcquery/ifcplusplus#255]
Hello everyone,

.cpp files from IfcPlusPlus/src/ifcpp/IFC4X3/lib/ come from a generator which have parse a schema file defined in express language programming. The following banner can be found at the beginning of all ifc class  .cpp files : 
`/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */`

Could you please put the generator that has been used with their inputs and please avoid inserting intermediate generated file in your project ? 

Best regards

**Comment by ifcquery** [comment]
Hi,
which intermediate files do you mean?

**Comment by emvivre** [comment]
You will find in the following links the list of files that have been generated automatically : [https://github.com/ifcquery/ifcplusplus/tree/master/IfcPlusPlus/src/ifcpp/IFC4X3/lib](https://github.com/ifcquery/ifcplusplus/tree/master/IfcPlusPlus/src/ifcpp/IFC4X3/lib)

These files have not been generate from a human. Please provide us all source code and inputs to generate files contained in https://github.com/ifcquery/ifcplusplus/tree/master/IfcPlusPlus/src/ifcpp/IFC4X3/lib 

Best regards

**Comment by ifcquery** [comment]
These are not intermediate files. These are source code files

**Comment by ifcquery** [comment]
The source code generator is not open source.
For commercial projects, I usually provide access to the source code generator for a small fee.
For commercial projects, please contact me at www.ifcquery.com
