### ISSUE TITLE
getTrimAngles regression

### ISSUE THREAD

**Issue by antoine-fresse** [ifcquery/ifcplusplus#257]
Hello,

After updating ifcplusplus to a newer version, I ran into some geometry issues on objects that worked fine before

I narrowed down to issue to a change in the logic of getTrimAngles compared to previous versions

I have a trimmed circle defined like this :
```
#101=IFCTRIMMEDCURVE(#102,(IFCPARAMETERVALUE(359.57216415768522)),(IFCPARAMETERVALUE(0.)),.T.,.PARAMETER.);
#102=IFCCIRCLE(#103,10.1509329597267);
```

The new code has an extra check : 
`if (trimAngle1 > 0 && trimAngle2 > 0 || trimAngle1 < 0 && trimAngle2 < 0) `that fails in my case because trimAngle2 is exactly 0
This result in taking the wrong arc from the circle (the "long way", instead of the "short way" in the case)

I tried looking up the spec, but I don't quite understand exactly what we are supposed to do in this corner case. 

I changed the checks to use >= and <= for our application for now, but I not sure if it might cause other issues for other cases I haven't encountered yet

**Comment by antoine-fresse** [comment]
here is a file that doesn't display properly in the sample viewer
[bug_circle.zip](https://github.com/ifcquery/ifcplusplus/files/13518660/bug_circle.zip)

**Comment by ifcquery** [comment]
With the latest change, it looks good:

![2023-12-01 10_51_36-test_bug_circle ifc](https://github.com/ifcquery/ifcplusplus/assets/11755247/417942a7-99ac-4f85-aba4-1fb4dbd3c169)
