### ISSUE TITLE
Missing geometry data when reading elements outside IFCProject

### ISSUE THREAD

**Issue by thuytran1676** [ifcquery/ifcplusplus#260]
Reading files "Arg Plot Plan Equipment.ifc", "INST Equipment.ifc" using IFC++1.9 API. There are some geometry data missing.
1. "INST Equipment.ifc": Neither IFC++Viewer 1.8 nor 1.9 can view this file
![image](https://github.com/ifcquery/ifcplusplus/assets/139486000/eab6b6fd-1035-4a12-8e98-c9f5c098d9e6)

3. "Arg Plot Plan Equipment.ifc": IFC++Viewer 1.8 can view this file, but IFC++Viewer 1.9
![image](https://github.com/ifcquery/ifcplusplus/assets/139486000/0f4da312-9795-461e-a713-f2eefd7723ac)
[INST Equipment.zip](https://github.com/ifcquery/ifcplusplus/files/13717883/INST.Equipment.zip)
[Arg Plot Plan Equipment.zip](https://github.com/ifcquery/ifcplusplus/files/13717885/Arg.Plot.Plan.Equipment.zip)

**Comment by ifcapps** [comment]
You're welcome to contribute to this open source project.
If you work on a commercial project, you can receive a quote for implementations and support on www.ifcquery.com

**Comment by ifcquery** [comment]
This should be solved with previous update
