### ISSUE TITLE
Out of bounds vector in simplifyPolygon

### ISSUE THREAD

**Issue by antoine-fresse** [ifcquery/ifcplusplus#264]
Hello,

in the function simplifyPolygon (the one that takes a vector of vec2) inside GeomUtils.h there are multiple unsafe erase calls : polygon.erase(polygon.begin() + ii - 1); that cause a crash when ii is 0.

Looks like d2b0e9c4f550515acadb26120c2356649351a7ae messed things up

Regards,
Antoine

**Comment by ifcapps** [comment]
Hello,
thanks for reporting.
ii can never be 0, because it starts at 2.
Do you have an example model where a problem occurs?

**Comment by ifcquery** [comment]
Some changes are already made, so there is only this erase left:

```
size_t idx1 = ii % polygon.size();
polygon.erase(polygon.begin() + idx1);
```

polygon.size() is always > 1, so the iterator can never be at the end

**Comment by ifcquery** [comment]
This should be solved with previous update
