### ISSUE TITLE
src/viewer/OrbitCameraManipulator.cpp missing

### ISSUE THREAD

**Issue by nlosacco** [ifcquery/ifcplusplus#266]
Hi,

trying to generate the Makefile with CMake I get the error in the title.
Edited the filename in CMakeLists.txt toOrbit3DManipulator.cpp but I'm not sure it is correct.

**Comment by ifcapps** [comment]
Cmake does not find OpenSceneGraph any more, that's the only reason why the Linux version is not easy to build at the moment.
Without the viewer application, Cmake is easy to run also on Linux
