### ISSUE TITLE
Reader doesn't eat all the thrash spaces

### ISSUE THREAD

**Issue by aborkai** [ifcquery/ifcplusplus#275]
I came across an IFC file from SolidWorks 2021, which contained unnecessary amount of spaces e.g.:
`#4 = IFCORGANIZATION ( '', ' ','',$,$ ) ;`
I realized, the problem is only with the space between the last closing parenthesis and semicolon.
The reading algorithm fails, and the file is not really loaded. I suggest more robust space eating reading.
e.g.: 
```
// add case to space char into bufferedGetStepLine() in src/ifcpp/reader/ReaderUtil.cpp
case ' ':
{
	if( inString )
	{
		lineOut += (char)c;
	}
	continue;
}
```

By the way, the file loaded without problems in ifcpp 1.1
File attached for test
[Typ_4.zip](https://github.com/ifcquery/ifcplusplus/files/15318875/Typ_4.zip)

**Comment by ifcapps** [comment]
Thanks for the hint!
I'll take that in the next update
