### ISSUE TITLE
Conversion unit

### ISSUE THREAD

**Issue by ahmetbekcan** [ifcquery/ifcplusplus#276]
Although the length unit in IFC file is millimeter, it seems like the converted shapes' coordinates are in meters.

**Comment by ifcapps** [comment]
Correct. That is intended

**Comment by ahmetbekcan** [comment]
Hi, thank you for the info. I assume that dividing the lengths with getLengthInMeterFactor() would solve this issue then.

**Comment by ifcapps** [comment]
It makes sense to have the geometry in a consistent length, area, volume unit (m, m², m³).
Of course you can mulitply it with some factors, but that will probably cause issues.
