### ISSUE TITLE
IFC 4x3. version 2.3 tag number has (,) from locale

### ISSUE THREAD

**Issue by alas2** [ifcquery/ifcplusplus#279]
Creating IFC results in tags with , thousands separator, see below . Can we have locale independent (without ,)?
 
In WriterSTEP::writeModelToStream(), I think, the fix is to add the below line

std::stringstream tmpStream;
tmpStream.imbue(std::locale("C"));  // To make it locale independent. 

#3,223= IFCCARTESIANPOINT((1163.3756274575,175.160611351,0.));
#3,224= IFCCARTESIANPOINT((1163.5746566147,175.1455190069,0.));
#3,225= IFCCARTESIANPOINT((1163.7737106008,175.1307577364,0.));
#3,226= IFCCARTESIANPOINT((1163.9727885982,175.1163239009,0.));
#3,227= IFCCARTESIANPOINT((1164.1718898077,175.1022138599,0.));
#3,228= IFCCARTESIANPOINT((1164.3710134477,175.0884239704,0.));
#3,229= IFCCARTESIANPOINT((1164.5701587546,175.0749505878,0.));

**Comment by ifcquery** [comment]
Thanks for the hint.
Just added it to the tmpStream.
