### ISSUE TITLE
IFC4X3. Reading unknow entities are NOT logged or sent to the message call back.

### ISSUE THREAD

**Issue by alas2** [ifcquery/ifcplusplus#280]
Can the err_unknown_entity  content be sent to the message call back?

I think, 

In **ReaderSTEP.cpp, void ReaderSTEP::readData(std::istream& read_in, std::streampos file_size, shared_ptr<BuildingModel>& model)**

at the end of the function need to add :

**if (err_unknown_entity.tellp() > 0)
{
         messageCallback(err_unknown_entity.str(), StatusCallback::MESSAGE_TYPE_UNKNOWN_ENTITY, __FUNC__);
}**

Can we please suggest to have a new message type, MESSAGE_TYPE_UNKNOWN_ENTITY,  for unknown entity? It will help us.

Thanks,

[Alignment.zip](https://github.com/user-attachments/files/15542364/Alignment.zip)

**Comment by ifcapps** [comment]
Sorry for the late reply.
I added it to ReaderSTEP
