### ISSUE TITLE
Bad geometry data for entity "Basic Wall:Exterior - Insulation on Masonry:139857"

### ISSUE THREAD

**Issue by thuytran1676** [ifcquery/ifcplusplus#281]
Steps to reproduce: version 2.4
1. Import Ifc file Architectural.ifc
2. Select and isolate entity "Basic Wall:Exterior - Insulation on Masonry:139857"
3. See video "GuideToNavigateToIssue.mp4" to find the issue 

Unexpected outcome:
1. There are 2 windows which are not subtracted geometry data correctly
![image](https://github.com/ifcquery/ifcplusplus/assets/139486000/1656a159-c971-4073-8713-dc838455dfab)

3. Missing a piece of geometry  data for that wall
![image](https://github.com/ifcquery/ifcplusplus/assets/139486000/e64b52ff-0520-4478-9ba7-ae4ba1673482)

https://github.com/ifcquery/ifcplusplus/assets/139486000/b5df46fa-1d6a-4eb8-bb36-87f17a35cf80

[Architectural.zip](https://github.com/user-attachments/files/16021250/Architectural.zip)

**Comment by ifcquery** [comment]
This should be fixed with current version:

![Screenshot 2024-08-09 112645](https://github.com/user-attachments/assets/46c296cb-403f-4d77-98c3-5ecdb0bd49d0)
