### ISSUE TITLE
Incorrect mesh generation of IfcRevolvedAreaSolid when using a hollow profile

### ISSUE THREAD

**Issue by simpk20** [ifcquery/ifcplusplus#38]
As I mentioned above, Ifc++ generates wrong shape (mesh) of IfcRevolvedAreaSolid when a polygon with an inner hole is used as its profile. When running in Debug mode (using MSVC 2010 on Windows 7), it crashes due to incorrect index of the vertices.  

When I look into the source, in triangulator.cpp of CARVE library, it seems function incorporateHolesIntoPolygon()  is the cause of the problem: 

void
carve::triangulate::incorporateHolesIntoPolygon(
    const std::vector<std::vector<carve::geom2d::P2> > &poly,
    std::vector<std::pair<size_t, size_t> > &result,
    size_t poly_loop,
    const std::vector<size_t> &hole_loops) {
  typedef std::vector<carve::geom2d::P2> loop_t;
 
  size_t N = poly[poly_loop].size();
 
  // work out how much space to reserve for the patched in holes.
  for (size_t i = 0; i < hole_loops.size(); i++) {
    N += 2 + poly[hole_loops[i]].size();
  }
 
  ...
 
}

in the for loop, It seems to me that the number '2' in the right-hand side of the variable N is Euler's number, which is v-e+f = 2 -2g. In this case, where the profile has a hole in it, the number should be 0, not 2, because g is 1. Is that right?

In my sample .ifc file, entity #605337 is the one having the symptom I'm describing. 

For the sample .ifc file, please download it from the link below:
https://drive.google.com/file/d/0B--Amqgu71ncRUN1T2lmQjFkUk0/view?usp=sharing

**Comment by ifcquery** [comment]
The last commit fixes the issue with IfcRevolvedAreaSolid. If a problem with it still occurs, please let me know.
