### ISSUE TITLE
Linking CXX executable ../Debug/SimpleViewerExample failed under Linux

### ISSUE THREAD

**Issue by ghost** [ifcquery/ifcplusplus#39]
Hi,

IfcPlusPlus' compilation was OK (I downloaded the last master release), but when Linking CXX executable ../Debug/SimpleViewerExample () I got this error :

> Linking CXX executable ../Debug/SimpleViewerExample
> /usr/bin/ld: cannot find -lIfcPlusPlusGeometry
> collect2: error: ld returned 1 exit status
> SimpleViewerExample/CMakeFiles/SimpleViewerExample.dir/build.make:618: recipe for target 'Debug/SimpleViewerExample' failed
> make[2]: **\* [Debug/SimpleViewerExample] Error 1
> CMakeFiles/Makefile2:178: recipe for target 'SimpleViewerExample/CMakeFiles/SimpleViewerExample.dir/all' failed
> make[1]: **\* [SimpleViewerExample/CMakeFiles/SimpleViewerExample.dir/all] Error 2
> Makefile:75: recipe for target 'all' failed
> make: **\* [all] Error 2

At this point,

> find -name _geo_
> ./Carve/CMakeFiles/carve.dir/src/common/geometry.cpp.o
> ./Carve/CMakeFiles/carve.dir/src/lib/geom3d.cpp.o
> ./Carve/CMakeFiles/carve.dir/src/lib/geom.cpp.o
> ./Carve/CMakeFiles/carve.dir/src/lib/geom2d.cpp.o
> ./Carve/src/common/geometry.cpp
> ./Carve/src/common/geometry.hpp
> ./Carve/src/common/geom_draw.cpp
> ./Carve/src/common/geom_draw.hpp
> ./Carve/src/lib/geom2d.cpp
> ./Carve/src/lib/geom3d.cpp
> ./Carve/src/lib/geom.cpp
> ./Carve/src/include/carve/geom_impl.hpp
> ./Carve/src/include/carve/geom2d.hpp
> ./Carve/src/include/carve/geom3d.hpp
> ./Carve/src/include/carve/geom.hpp
> ./IfcPlusPlusGeometry/src/ifcppgeometry

It seams to be basic, but I don't know a lot of things on compiling or linking (sorry)...

Can you help me, please ?

**Comment by ifcquery** [comment]
Hi,
you don't need to link IfcPlusPlusGeometry, since it is header-only.
So you can simply remove -lIfcPlusPlusGeometry from your build.

**Comment by lecam-conseil** [comment]
Hi,
Replacing TARGET_LINK_LIBRARIES(SimpleViewerExample IfcPlusPlusGeometry)
by TARGET_LINK_LIBRARIES(SimpleViewerExample)
in /SimpleViewerExample/CMakeLists.txt
seems to work.
Thank you

**Comment by berndhahnebach** [comment]
Hi Fabian, 
Hi lecam-conseil, 

@lecam-conseil What distribution are you on?
I get linking errors inspite of removing IfcPlusPlusGeometry from TARGET_LINK_LIBRARIES

    bhb@ubuntuVM:~/Documents/ifcplusplus/ifcplusplus-testen/build$ make
    ...
    [100%] Building CXX object SimpleViewerExample/CMakeFiles/SimpleViewerExample.dir/qrc_ifcplusplus.cxx.o
    Linking CXX executable ../Debug/SimpleViewerExample
    /usr/bin/ld: CMakeFiles/SimpleViewerExample.dir/src/cmd/LoadIfcFileCommand.cpp.o: undefined reference to symbol '_ZN7osgText8TextBase21setAutoRotateToScreenEb'
    /usr/lib/libosgText.so.99: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    SimpleViewerExample/CMakeFiles/SimpleViewerExample.dir/build.make:615: recipe for target 'Debug/SimpleViewerExample' failed
    make[2]: *** [Debug/SimpleViewerExample] Error 1
    CMakeFiles/Makefile2:175: recipe for target 'SimpleViewerExample/CMakeFiles/SimpleViewerExample.dir/all' failed
    make[1]: *** [SimpleViewerExample/CMakeFiles/SimpleViewerExample.dir/all] Error 2
    Makefile:72: recipe for target 'all' failed
    make: *** [all] Error 2
    bhb@ubuntuVM:~/Documents/ifcplusplus/ifcplusplus-testen/build$ 

If I try  to explicit add the  /usr/lib/libosgText.so.99 to CMakeLists.txt by 

    INCLUDE_DIRECTORIES( ${INCLUDE_DIRECTORIES} ${OSGTEXT_INCLUDE_DIR} )
    TARGET_LINK_LIBRARIES(SimpleViewerExample ${OSGTEXT_LIBRARY} )

I get hundreds of undefined references ...

**Comment by lecam-conseil** [comment]
@berndhahnebach : I'm building with QtCreator under Xubuntu 14.10
I had the same error
I think you should add this to /SimpleViewerExample/CMakeLists.txt :
INCLUDE_DIRECTORIES( ${INCLUDE_DIRECTORIES} ${OSGTEXT_INCLUDE_DIR} )
give me a back, please

**Comment by berndhahnebach** [comment]
Ohh forgot to post that line. Yeah it is needed ...

Ahh here we are :-), runs on Debian Jessie :-)

    # SimpleViewerExample/CMakeLists.txt
    # add the lines
    INCLUDE_DIRECTORIES( ${INCLUDE_DIRECTORIES} ${OSGTEXT_INCLUDE_DIR} )
    TARGET_LINK_LIBRARIES(SimpleViewerExample ${OSGTEXT_LIBRARY} )
    # change line 
    TARGET_LINK_LIBRARIES(SimpleViewerExample IfcPlusPlusGeometry) 
    # to 
    TARGET_LINK_LIBRARIES(SimpleViewerExample IfcPlusPlus carve)

https://github.com/berndhahnebach/IfcPlusPlus/commit/b9ced2573b23270cec160e9817aa8aabd7b52ccd

Fabian made a new commit yesterday. My fixes are based on the commit before. https://github.com/ifcquery/ifcplusplus/commit/afe041cc5d8459e57627cf654c4384dac3b2eb96

**Comment by ifcquery** [comment]
Hi,
as Bernd said, I took the obove cmake fix into the last commit. Hope it works now on linux :)

**Comment by berndhahnebach** [comment]
https://github.com/berndhahnebach/IfcPlusPlus/commits/latestgit66bhb

**Comment by berndhahnebach** [comment]
@Fabian
Qt4 vs. Qt5 problem resists. See commit link in last comment. I changed cmake in a way Qt4 is only used on Linux. See last chapter in README file --> https://github.com/berndhahnebach/IfcPlusPlus/blob/master/README.md

**Comment by ifcquery** [comment]
Release of Qt5 has been three years ago. It does make no sense to use > 3 years old software like Qt4...

**Comment by berndhahnebach** [comment]
Hi Fabian, 

Thanks for your answer. It's just a commit of a few lines. It's easy to merge it by myself if you upgrade your repo. I'm gone continue to support IfcPlusPlus for Linux at the master branch on my repo (https://github.com/berndhahnebach/IfcPlusPlus/). The branch is only upgraded if the viewer compiles and runs on Debian and Ubuntu using standard distribution binary packages.

regards bernd

**Comment by berndhahnebach** [comment]
Hi Fabian, 

can be closed IMHO.

Bernd
