### ISSUE TITLE
windows binary

### ISSUE THREAD

**Issue by berndhahnebach** [ifcquery/ifcplusplus#40]
Hi Fabian,

do you provide windows binary for the viewer somewere? The link on http://ifcplusplus.com/download.php still points to google code.

Bernd

**Comment by ifcquery** [comment]
Hi Bernd,
I just updated http://ifcplusplus.com/download.php, a binary of ifcquery viewer can be downloaded from there. Not the binary of SimpleViewerExample though.
Fabian

**Comment by berndhahnebach** [comment]
Wow even better, thanks Fabian.

**Comment by berndhahnebach** [comment]
Hi Fabian, 

I still only do Linux builts only. Would you provide a newer Windows binary? The one provided on http://www.ifcplusplus.com/download.php is quite outdated. September 18th 2015

cheers bernd
