### ISSUE TITLE
IfcPPModel::setIfcSchemaVersion does not affect the output of IfcPPWriterSTEP::writeModelToStream

### ISSUE THREAD

**Issue by PanicSheep** [ifcquery/ifcplusplus#46]
If i load a IfcPPModel from a file, then alter the version and write that back to a file, the version didn't change. This happens because:

```
IfcPPModel * ifc_model;
ifc_model->setIfcSchemaVersion(IfcPPModel::IfcPPSchemaVersion(L"IFC2x3", IfcPPModel::IfcPPVersionEnum::IFC2X3));
```

calls

```
void IfcPPModel::setIfcSchemaVersion( IfcPPSchemaVersion& ver )
{
	m_ifc_schema_version.m_IFC_FILE_SCHEMA = ver.m_IFC_FILE_SCHEMA.c_str(); // (§1)
	m_ifc_schema_version.m_ifc_file_schema_enum = ver.m_ifc_file_schema_enum; // (§2)
}
```

but writing the header back to the file

```
shared_ptr<IfcPPWriterSTEP> writer(new IfcPPWriterSTEP());
std::stringstream ss;
writer->writeModelToStream(ss, ifc_model);
```
calls `encodeStepString(ifc_model-->getFileHeader())`

which calls `IfcPPModel::getFileHeader() { return m_file_header; } // (§3)`

so (§1) and (§2) don't affect (§3).

**Comment by ifcquery** [comment]
Thank you for the comment. The schema version and file header is indeed inconsistent at the moment.
All IFC classes in IFC++ are generated from the IFC4 schema. Entities from files with older versions are converted during loading. So the model schema is always IFC4, and it does not make sense to write a different version to a file when exporting.
I fixed the version and removed the setIfcSchemaVersion method.
One could still manually write a different version to IfcPPModel::getIfcSchemaVersion().m_IFC_FILE_SCHEMA = ..., so it will be written to file, but I don't think it makes much sense.

**Comment by PanicSheep** [comment]
> I fixed the version and removed the setIfcSchemaVersion method.

That's a very reasonable fix.
