### ISSUE TITLE
fix in cmake

### ISSUE THREAD

**Issue by berndhahnebach** [ifcquery/ifcplusplus#47]
Hi Fabian,

some small fix in cmake. https://github.com/berndhahnebach/IfcPlusPlus/commits/fixcmake

cheers bernd

**Comment by ifcquery** [comment]
Hi Bernd,

thanks :)


---------------------------------------------
Fabian Gerold
Mail: fabian.gerold@gmail.com
Phone: (+49)176 55119954

2016-04-21 13:40 GMT+02:00 Bernd Hahnebach <notifications@github.com>:
