### ISSUE TITLE
Instantiation of abstract class

### ISSUE THREAD

**Issue by PanicSheep** [ifcquery/ifcplusplus#49]
Classes that the Ifc standard declares as abstract are not abstract c++ classes.
This leaves you with the possibility of creating an instance of them.

Should we make the corresponding c++ classes abstract, or am I getting the idee of the ifc-abstract wrong?

**Comment by ifcquery** [comment]
Theoretically, abstract entities should result in an abstract class in C++.
But until now it never was an issue, so actually I don't want to spend time on it.

**Comment by PanicSheep** [comment]
As it turns out there are numerous files that contain abstract ifc classes. So having them non-abstract in ifc++ enabled me to process them nevertheless, which is a good thing ;-)
