### ISSUE TITLE
SimpleViewerExample show nothing

### ISSUE THREAD

**Issue by insisthzr** [ifcquery/ifcplusplus#51]
Hi Fabian.
I use your project compiled with win64-msvc2013.
When I  use SimpleViewerExample to open a small model,
nothing display.
Then I try a big model,
it crashs.

**Comment by ifcquery** [comment]
Hi,
can you attach the small and the big model? Otherwise I can't figure out or say anything to that...

**Comment by berndhahnebach** [comment]
Try this file. The viewer has been displaying this file for years including the latest commits version.
https://github.com/berndhahnebach/IfcPlusPlus/blob/master/IfcOpenHouse.ifc

**Comment by ifcquery** [comment]
I just loaded the file into SimpleViewerExample, compiled with msvc2015, x64. No problems so far. 
Can you step through the code to locate the problem?

**Comment by berndhahnebach** [comment]
@Fabian
Since it seams insisthzr is not able to open any file at all I (Bernd) provided the linkt to the file, because for sure the viewer is able to display this file. 

cheers bernd

**Comment by ifcquery** [comment]
@Bernd
ah, ok. Thanks :)

**Comment by insisthzr** [comment]
I used berndhahnebach's ifc to test,
It seems only show ifcsite without its child node.

**Comment by insisthzr** [comment]
sorry,it seems I use incorrect qt version.
but when I run a big model,
it still crash.
In file intersect_face_division.cpp,
std::copy(base_loop.begin() + pos, base_loop.begin() + e1_1, std::back_inserter(out));
pos > e1_1,
I want to use your code to make a demo,
but I can't sovleout this bug.
This is the ifc file below
https://github.com/insisthzr/ifcplusplus/blob/master/EPP%20WWT.ifc

**Comment by ifcquery** [comment]
The file intersect_face_division.cpp is part of Carve, which is a 3rd party library like Qt.
So to solve that, a deeper analysis and fix is necessary, probably inside Carve.

**Comment by berndhahnebach** [comment]
Wow a cool model made with tekla. The file opens fine for me on Linux with latest commit (84). It opens too with the outdated win binary from ifcplusplus.com (september 2015). But it take really long and has dozens of warnings.

cheers bernd

![screen-lin-84](https://cloud.githubusercontent.com/assets/6129869/16339803/edcde824-3a24-11e6-8c0d-2e6fff7b8a8c.jpg)

**Comment by ifcquery** [comment]
On my windows machine it loads in less than 5 seconds :)
But only with the older version of Carve. Something has changed obviously. Eventually I can fix it some time.
