### ISSUE TITLE
Compiling IFCPlusPlus with VS2015 create huge library

### ISSUE THREAD

**Issue by ichimv** [ifcquery/ifcplusplus#53]
We compiled IFCPlusPlus with VS2015 and size of ifcplusplus.lib is 3 GB. We created a dll for it but still have instability issue.

Do you have plans to make a project in VS2015 to generate a DLL for  ifcplusplus library?

A similar issue was reported [here](http://stackoverflow.com/questions/36469402/compiling-ifcplusplus-with-vs2015-create-huge-libraries).

**Comment by ifcquery** [comment]
It already is a dll project. The .lib is only an import library and 10 MB big on my machine.

**Comment by AlenSmailovic** [comment]
But for x86 .lib is still and up to 800 MB. Can you please solve this issue, like in x64 case?

**Comment by ifcquery** [comment]
For me it makes no sense to use IFC in a 32 bit context with limited memory. So I don't maintain 32 bit project settings. If you need 32 bit, you can copy the settings from the 64 bit project setttings in VS.

**Comment by ichimv** [comment]
Problem is solved indeed. Thank you.
