### ISSUE TITLE
Question : OpenCascade support

### ISSUE THREAD

**Issue by Valzul** [ifcquery/ifcplusplus#56]
Hi there,

just a little question about the OpenCascade geometry support. Why did you put it in your project ?
Did you just wanted to add the support for ifcplusplus to become more compatible, or does it achieve something else that OSG doesn't do ?

I'm a bit curious about this, just for my own information.

Anyway thank you for your work !

**Comment by ifcquery** [comment]
Currently, I work with OCC, so I added a simple implementation to IFC++. It needs optimization though. 
Carve is not maintained any more as far as I know. But it still has a much better performance than OCC.
So depending on the purpose, OCC or Carve is the better choice, both possible now with IFC++

**Comment by Valzul** [comment]
I see your point there concerning performance ( given that AFAIK OCC allows more controls other it's objects types than OSG, but I could be wrong ... ).

Concerning your current work with OCC, did you have to make the choice between OCC and some other frameworks  ( like OSG )  at some point of your projects ? Is it work related or is it just for the sake of learning a new framework ?

Right now my company is confronting thoughts about the choice to use OSG or OCC for our dev, given that we are working on modeling Computer aided design in 3D with the possibilities to manipulate entities in those models in order to produce 2D casting, extruding, piercing, adding new items into the 3D model and such ... ( That's where Ifc++ comes in handy for sure 👍 )

Do you have some thoughts about this ? Did you find yourself in similar projects ?
Any feedback would be interesting.

Thanks

( and perhaps helps others too .. btw )

**Comment by ifcquery** [comment]
OSG is just a rendering library, basically an abstraction layer ontop of OpenGL for convenience. OSG is used in IFC++ as rendering library.
OCC is a geometric model with a large number of functions to manipulate geometric objects, for example boolean operations.
OCC also contains a rendering framework, but it is so bad, I don't think anyone seriously uses it.
I would say this topic is not really an "issue" in IFC++, but more a general question.
Please feel free to contact me for professional support for your project via email: fabian dot gerold at gmail dot com
