### ISSUE TITLE
HEADER and ENDSEC are exported twice

### ISSUE THREAD

**Issue by alas2** [ifcquery/ifcplusplus#59]
void IfcPPWriterSTEP::writeModelToStream( std::stringstream& stream, shared_ptr<IfcPPModel> model )
{
.
.
.
const std::wstring& file_header_wstr = model->getFileHeader();
  	std::string file_header_str = encodeStepString( file_header_wstr );
- 	stream << "ISO-10303-21;\n";
- 	stream << "HEADER;";         _**// Should be removed as is already in model->getFileHeader().**_
  	stream << file_header_str.c_str();
- 	stream << "ENDSEC;\n";         _**// Should be removed as is already in model->getFileHeader().**_
  	stream << "DATA;\n";

.
.
.
.

}

**Comment by JickYang** [comment]
@alas2  Hi , I have some problem about building the project. The system is 14.04LTS-64bit. The code is up tp date. When I use cmake to build the project, it show me the error log
```
jick@jick-virtual-machine:~/ifcplusplus/build$ cmake ../
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- ------------------------------------------------------------------------
-- Boost version: 1.54.0
-- Boost version: 1.54.0
-- Qt5 is used
-- Found osgDB: /usr/lib/libosgDB.so
-- Found osgUtil: /usr/lib/libosgUtil.so
-- Found osgGA: /usr/lib/libosgGA.so
-- Found osgFX: /usr/lib/libosgFX.so
-- Found osgSim: /usr/lib/libosgSim.so
-- Found osgText: /usr/lib/libosgText.so
-- Found osgQt: /usr/lib/libosgQt.so
-- Found osgViewer: /usr/lib/libosgViewer.so
-- Found osg: /usr/lib/libosg.so
-- Found OpenThreads: /usr/lib/libOpenThreads.so
-- Found OpenSceneGraph: /usr/lib/libosgDB.so;/usr/lib/libosgUtil.so;/usr/lib/libosgGA.so;/usr/lib/libosgFX.so;/usr/lib/libosgSim.so;/usr/lib/libosgText.so;/usr/lib/libosgQt.so;/usr/lib/libosgViewer.so;/usr/lib/libosg.so;/usr/lib/libOpenThreads.so (found version "3.2.0")
-- Boost version: 1.54.0
-- Configuring done
CMake Error at IfcPlusPlus/CMakeLists.txt:51 (ADD_LIBRARY):
  Cannot find source file:

    src/ifcpp/IfcPPEntityBroker.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


-- Build files have been written to: /home/jick/ifcplusplus/build
```
Can you tell me how do you build this project successfully? Thanks.

**Comment by ifcquery** [comment]
Thanks for the hint to the duplicate HEADER and ENDSEC output. It is fixed now.
Also the cmake files are updated, so that should work now also on linux. Please open a separate issue in case cmake does not work, or just drop me an email.

**Comment by berndhahnebach** [comment]
@JickYang 

would you give some feedback if you got uptodate IFC++ compiled  on Linux. I have not been compiling it for quite a while. You may be interested in https://github.com/berndhahnebach/IfcPlusPlus/commits/master

bernd

**Comment by JickYang** [comment]
@berndhahnebach  Thank you. The cmake files had update, now I can build the project successfully.

**Comment by JickYang** [comment]
@ifcquery  OK, I will test to compile this project and send you an email if you have any questions. XD!

**Comment by berndhahnebach** [comment]
> @berndhahnebach Thank you. The cmake files had update, now I can build the project successfully.

I got errors on Linux ... See https://github.com/ifcquery/ifcplusplus/issues/63 How did you get around them ...   

Cheers bernd
