### ISSUE TITLE
IfcPPReaderSTEP::readStepLines() does not loge an error if unknown entity encountered

### ISSUE THREAD

**Issue by alas2** [ifcquery/ifcplusplus#61]
In IfcPPReaderSTEP::readStepLines() around line 451 in IfcPPReaderSTEP.cpp. Does not log an error if there is an exception of UnknownEntityException is caught and it is not "IFC2DCOMPOSITECURVE"

	
`catch(UnknownEntityException& e)
{
	std::string step_line_fix = step_line;
	std::string unknown_keyword = e.m_keyword;

	if( unknown_keyword.compare( "IFC2DCOMPOSITECURVE" ) == 0 )
	{
		size_t pos_find = step_line_fix.find( "IFC2DCOMPOSITECURVE" );
		step_line_fix = step_line_fix.erase( pos_find + 3, 2 );
	
		try
		{
			readSingleStepLine( step_line_fix, entity_read_obj );
		}
		catch( UnknownEntityException& )
		{
			if( unkown_entities.find( unknown_keyword ) == unkown_entities.end() )
			{
#ifdef IFCPP_OPENMP
#pragma omp critical
#endif
				{
					unkown_entities.insert( unknown_keyword );
					err_unknown_entity << "unknown IFC entity: " << unknown_keyword << std::endl;
				}
			}
		}
	}
	**_else // Need to be added
	{
		unkown_entities.insert( unknown_keyword );
		err_unknown_entity << "unknown IFC entity: " << unknown_keyword << std::endl;
	}_**
}`

**Comment by ifcquery** [comment]
Thanks for the hint! I just added it in the repository.
