### ISSUE TITLE
Performance issue with IfcPPModel::getMaxUsedEntityId()

### ISSUE THREAD

**Issue by alas2** [ifcquery/ifcplusplus#62]
This function uses a map whether it is ordered or un_ordered, it can be very slow if there is a big IFC file as it needs to loop through each entity. Can we change it to the below code ?

`int IfcPPModel::getMaxUsedEntityId()
{
	if( m_map_entities.size() == 0 )
	{
		return 0;
	}
	int max_used_id = 1;
	for( auto it = m_map_entities.begin(); it != m_map_entities.end(); ++it )
	{
		if( it->first > max_used_id )
		{
			max_used_id = it->first + 1;
		}
	}
	//m_map_entities.rbegin()->first;
	return max_used_id;

        ////////////////////////////////////////        Change to  . Need to declare and initialise m_max_used_id to 1
	int returnValue = m_max_used_id;
	m_max_used_id++;
	return returnValue;
         ///////////////////////////////
}`

**Comment by PanicSheep** [comment]
Don't forget about non-empty models.
But the speed of this function is a minor problem for me aswell. I will be able to fix it in about a month or two.

**Comment by ifcquery** [comment]
Did you measure the time of getMaxUsedEntityId()? It should be a really small amount of time.

**Comment by alas2** [comment]
@ifcquery, 

Yes, for one job tried to write to IFC++ 4 and it took very long time and didn't even finish and had to stop the process.  The bottle neck was ifcPPModel::getMaxUsedEntityId()

I think you can avoid using the maps all we want is just unique entity Id.
Thanks :).

**Comment by PanicSheep** [comment]
Nice solution with using std::map. Good catch.

**Comment by ifcquery** [comment]
:)
