### ISSUE TITLE
wrong tesselated Wall

### ISSUE THREAD

**Issue by loebl** [ifcquery/ifcplusplus#67]
Hello,

I am currently using IfcPlusPlus to import IFC files into my project.

I noticed, that in the [example model from the ifcwiki](http://www.ifcwiki.org/index.php?title=KIT_IFC_Examples) a wall is wrong tesselated.
Specifically in the Institute model, the wall with entity id 197939 looks wrong.

I extracted it with IfcQuery and attached it. In the old IfcQuery from the website it looks good, but with the SimpleViewer built from 01.11.2017 (and in my application) it looks wrong. I attached a screenshot.

I am sure the problem is inside IfcPlusPlus/Carve geometry, if I have the time I might try to hunt the bug.

![ac20_wall](https://user-images.githubusercontent.com/25525942/33661142-e00f3b4e-da86-11e7-989e-a3488c0b7dc5.png)

[ac20-institute-wall.zip](https://github.com/ifcquery/ifcplusplus/files/1535076/ac20-institute-wall.zip)

**Comment by loebl** [comment]
Update: I narrowed the problem down to the following: In CSG_Adapter.h: `simplifyMesh` `carve::mesh::MeshSimplifier::mergeCoplanarFaces` is used to merge all faces in a plane (and in subsequent steps to eliminate unneeded vertices). Unfortunately this results in tesselation errors, if the face openings are made in a specific order.

The background is, that the used triangulation algorithm, ear clipping, is restricted to simple polygons without intersections and holes. Polygons with holes can be tesselated by cutting the poly open, meaning some specific edges have to exist. The merge step under the mentioned conditions actually eliminates the important edge and leaves an edge that is intersecting the poly (or rather a colinear edge, but its nonetheless an invalid poly for ear clipping).

As a workaround for now I will disable lines 788-799 in CSG_Adapter.h (the mergeCoplanarFaces step) in our code. This results in more geometry generated, but at least there are no tesselation errors. Maybe I look into writing a functon which checks and fixes the generated polygon, but I can't promise this at the moment.

**Comment by loebl** [comment]
Another update: disabling merging of coplanar faces trigers a bug in `mergeAlignedEdges`. I have a fix in my branch, should you consider applying the fix mentioned before.

If you are interested in a patch, I would move the changes to a separate branch for a pull request.

**Comment by ifcquery** [comment]
Hi, sorry for the late reply. I just checked the file ac20-institute-wall.zip. Indeed, the method "mergeCoplanarFaces" from carve and also my own method "simplifyMesh" need some improvements.
It would be great if you could make a pull request of your fix. Thanks!
