### ISSUE TITLE
Compilieren von ifcplusplus in Debian 9 (stretch) x86_64 Probleme und Lösungen

### ISSUE THREAD

**Issue by jmfischer2017** [ifcquery/ifcplusplus#71]
Hier meine Erfahrung bei Compilieren von ifcplusplus in Debian 9 (stretch) x86_64

- am  14/12∕2017 : git clone https://github.com/ifcquery/ifcplusplus/

Konfigurieren:
Hürde 1: in den CmakeLists.txt: CMAKE_MINIMUM_REQUIRED (VERSION 3.9.4). Aber 	stretch hat die Version 3.7.2-1 und stretch_Backbord enthält kein cmake.
Lösung 1: Die Version 3.9.5-1 von „testing“ (zur zeit „Buster“) holen mit:
	apt-get install -t testing cmake
	und da ich auch cmake-qt-gui benutze:
	apt-get install -t testing cmake-qt-gui
	die Version von qtbase5-dev wurde auch an gemotzt, also:
	apt-get install -t testing qtbase5-dev

Hürde 2 : für osg suchte cmake nach debug library die er nicht fand.
Lösung 2: für alle OSGxxx_LIBRARY_DEBUG den selben wert wie für OSGxxx_LIBRARY 	eingeben.

Make.
Hürde 3: Da kamen die selben Fehler wie bei https://github.com/ifcquery/ifcplusplus/issues/63 	gemeldet. Mit error: ‘ptrdiff_t’ does not name a type,  typedef ptrdiff_t difference_type;

Lösung 3: folgende Dateien habe ich ergänzt:
	ifcplusplus/Carve/src/include/carve/mesh_impl.hpp   + #include <cstddef>
	ifcplusplus/Carve/src/include/carve/polyhedron_base.hpp   + #include <cstddef>
	ifcplusplus/Carve/src/include/carve/vector.hpp   + #include <algorithm>

	Habe die Lösung hier gefunden: https://gcc.gnu.org/gcc-4.6/porting_to.html
	und hier :  „http://www.cplusplus.com/articles/NhA0RXSz“

Hürde 4, Lösung 4: in https://github.com/berndhahnebach/IfcPlusPlus/commit/3dca69b

Dann lief make bis 99% ab, aber dann kamm ein Problem mit osgDB/fstream. Ich hatte auch libopenscenegraph-dev von „testing“ installiert und auch alle anderen osg Pakete. Nach langem suchen habe ich schließlich openscenegrah von https://github.com/openscenegraph/OpenSceneGraph in /usr/local installiert ohne Probleme. Die Debian Pakete habe ich ab instaliert.

Endlich war ifcplusplus compiliert. Dann noch ein „Make install“ und ein ldconfig. „libcarved.so“ ist in /usr/local/bin gelandet?? die Datei habe ich nach usr/local/lib verschoben.

Ab da konnte ich SimpleViewerExampled starten aber bei klicken auf  „Choose file“ hängt sich das Programm auf, und im Terminal erscheint die Meldung:
„Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged
Ich kann trotzdem ifc Dateien laden, indem ich sie beim starten als Parameter eingebe.

**Comment by berndhahnebach** [comment]
hier meine änderungen für debian stretch
https://github.com/berndhahnebach/IfcPlusPlus/commits/fggit108

ich habe osg selber übersetzt und kann auch files mit dem dialog öffnen. 

@Fabian, PR folgt ...

**Comment by berndhahnebach** [comment]
https://github.com/ifcquery/ifcplusplus/pull/72

**Comment by berndhahnebach** [comment]
https://github.com/ifcquery/ifcplusplus/pull/73

dann sollte die carve library gleich am richtigen ort sein :-)

**Comment by berndhahnebach** [comment]
https://gist.github.com/berndhahnebach/e4d57634fe7eebbae537bf3da1b1b95a

**Comment by berndhahnebach** [comment]
in Bezug auf das File open Problem siehe auch die Readme meines alten qt4 branches ... https://github.com/berndhahnebach/ifcplusplus/blob/latestqt4/README.md

Due to a bug in Ubuntu Standard QtGUI theme the "Choose File" Dialog does not work properly on Trusty Tahr. Workaround (assumed you are in Directory Debug):

    start IfcPlusPlusViewer together with a ifc file from the shell
        ./SimpleViewerExample pathtotheifcfile/theifcfile.ifc
        ./SimpleViewerExample ../../IfcOpenHouse.ifc
    start IfcPlusPlusViewer with a different style
        ./SimpleViewerExample -style=fusion
    change the GUI style of all Qt applications on Ubuntu
        sudo apt-get install qt4-qtconfig
        launch qtconfing-qt4
        change Select GUI Style (Cleanlooks works for me.)
        don't forget to save your changes

bernd
