### ISSUE TITLE
IFC++ writes commas instead of dots

### ISSUE THREAD

**Issue by loebl** [ifcquery/ifcplusplus#77]
I noticed, that IFC++ writes commas instead of dots on my machine
Win 10 x64, IFC++ build with VS 2015 x64

Although it tries to set the locale using setlocale in `IfcPPWriterSTEP::writeModelToStream` it doesn't seem to have an effect.
As far as I know, the correct way would be to use imbue:
```
void IfcPPWriterSTEP::writeModelToStream( std::stringstream& stream, shared_ptr<IfcPPModel> model )
{
    stream.imbue(std::locale("C"));
```

At least if I imbue the C locale before calling `writeModelToStream` I get the expected results.
If you prefer I can open a pull request.

**Comment by ifcquery** [comment]
Yes, you are right, thanks for the hint!
A pull request would be fine :)
