### ISSUE TITLE
Import of tesselated objects

### ISSUE THREAD

**Issue by loebl** [ifcquery/ifcplusplus#81]
As far as I have seen, the Carve geometry converter currently does not handle the [IfcTessellatedItem](http://www.buildingsmart-tech.org/ifc/IFC4/Add2TC1/html/schema/ifcgeometricmodelresource/lexical/ifctessellateditem.htm) classes.

Are there currently any plans in place to add support for these geometries? If there is currently nothing planned I might be able to write a patch for IFC++ (I currently can't estimate how long it would take, but as those usually don't need additional processing it shouldn't be that much additional code)

**Comment by ifcquery** [comment]
There is nothing planned yet. I would absolutely appreciate, if you added some implementation for this. I'll merge it as soon as you have it.

**Comment by loebl** [comment]
OK. I can't promise a specific date, but I might have something ready this month

**Comment by ifcquery** [comment]
That's perfectly fine, it's necessary but not urgent.
