### ISSUE TITLE
Type in IfcTriangulatedFaceSet wrongly parsed

### ISSUE THREAD

**Issue by loebl** [ifcquery/ifcplusplus#82]
Hi,

I am currently working on #81 and hit a bump in the road.
Short: The attribute `CoordIndex` of entity `IfcTriangulatedFaceSet` is wrongly parsed as entity reference list, instead of value list.

From my current point of knowledge does this problem arise from ifcquery/Express2SourceConverter when generating the entity source code. It tries to decide if it needs to create parsing code for types or for entities and wrongly decides for entity, as the type is not a basic type (it is a derived type)

Other affected entities are `IfcPolygonalFaceSet` (also CoordIndex) and `IfcColourRGBList` (attribute ColourList). All three are new entities in IFC 4 related to tessellated meshes and therefore currently rarely used (which is probably why this bug went unseen until now).

As this currently blocks my progress on testing my tessellated item parsing I try to fix this myself. If you have additional input/hints, it is appreciated.

**Comment by ifcquery** [comment]
Hi, thanks for the bug report. I just fixed it.

**Comment by loebl** [comment]
Working like a charm, thanks.
