### ISSUE TITLE
Define ENABLE_OPENMP crash the example

### ISSUE THREAD

**Issue by geobeans** [ifcquery/ifcplusplus#91]
When I compile ifcplusplus library having "ENABLE_OPENMP" define, loading an ifc file will crash.But compiling the ifcplusplus library removing the "ENABLE_OPENMP" define,loading an ifc file will success!
I use the VS2017 or VS2015,all the same problem! I don't know anybody encounters the same problem as me.

**Comment by loebl** [comment]
To use openMP in IFC++, there are severalt steps:
1. Compile the library with ENABLE_OPENMP defined
2. Enable openMP support in your compiler
3. In your application also define ENABLE_OPENMP and enable openMP in your compiler. The geometry converters are purely header files and will only be compiled on use in your application.

**Comment by geobeans** [comment]
ya! you are right! After I difine ENABLE_OPENMP in my applicaton, everyting is ok! Thanks very much!

**Comment by ifcquery** [comment]
The description by loebl is exactly right. 
I will add a checking routine (if possible) that gives a compile error when defines are not correct.
